import platform
info = []
info.append("SO: "+platform.system())
info.append("\n")
info.append("\n")
info.append("Version SO: "+platform.release())
info.append("\n")
info.append("\n")
info.append("Build SO: "+platform.version())
info.append("\n")
info.append("\n")
info.append("Procesador: "+platform.processor().split(" ")[0])
info.append("\n")
info.append("\n")
info.append("Arquitectura: "+platform.architecture()[0])
info.append("\n")
info.append("\n")
info.append("Python "+platform.python_version())
info.append("\n")
info.append("\n")
info.append("***Creadores***")
info.append("\n")
info.append("Jorge Gonzalez")
info.append("\n")
info.append("Maxim Macari")
info.append("\n")
info.append("Gabriel Revilla")
info.append("***************")